// <auto-generated>
// Questo file e' generato dal designer di Ide.App. Non modificarlo a mano:
// verra' sovrascritto ad ogni modifica del form nel designer.
// </auto-generated>
using System;
using Microsoft.AspNetCore.Components;
using VbControls;
using VbControls.Abstractions;

namespace RssFeedViewer.Pages;

public partial class Home
{
    [Inject]
    protected NavigationManager NavigationManager { get; set; } = default!;

    protected bool IsDesignMode => NavigationManager.Uri.Contains("design=true", StringComparison.OrdinalIgnoreCase);

    protected VbTextBoxVisual TextBox1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 0, Y = 24, Width = 200, Height = 28 },
        Text = "https://feeds.bbci.co.uk/news/rss.xml",
        Placeholder = "URL del feed RSS",
    };

    protected VbButtonVisual Button1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 279, Y = 22, Width = 120, Height = 32 },
        Text = "Carica ora",
    };

    protected VbTextBoxVisual TextBox2 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 0, Y = 84, Width = 200, Height = 28 },
        Text = "",
        Placeholder = "Titolo ultimo articolo",
        ReadOnly = true,
    };

    protected VbTextAreaVisual TextArea1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 0, Y = 128, Width = 250, Height = 100 },
        Text = "",
        Placeholder = "Contenuto ultimo articolo",
        ReadOnly = true,
    };

    protected VbTimerVisual Timer1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 453, Y = 82, Width = 32, Height = 32 },
        IntervalMs = 60000,
        Enabled = true,
    };

    protected VbHttpClientVisual HttpClient1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 453, Y = 162, Width = 32, Height = 32 },
        BaseAddress = "",
    };

    protected VbLabelVisual Label1 { get; } = new()
    {
        LayoutBox = new LayoutBox { X = 4, Y = 276, Width = 150, Height = 24 },
        Text = "In attesa del primo aggiornamento...",
    };

    protected override void OnInitialized()
    {
        base.OnInitialized();
        Timer1.Tick += Timer1_Tick;
    }
}
