using System.Globalization;
using System.Reflection;
using System.Text;
using VbControls.Abstractions;

namespace Ide.Designer;

/// <summary>
/// Modulo 7: genera i due file posseduti dal designer per ogni Form
/// (vincolo architetturale n.3): <c>{Form}.razor</c> e <c>{Form}.razor.designer.cs</c>.
/// Il terzo file, <c>{Form}.Behavior.cs</c>, e' scritto dallo sviluppatore e non viene
/// mai toccato da questa classe.
/// Rigenera sempre l'intero contenuto a partire dal modello in memoria: e' sicuro perche'
/// questi file non sono editati a mano.
/// Modulo 13: i controlli possono essere visuali o non-visuali (sezione 2.1 di
/// ARCHITECTURE.md) - il generatore tratta entrambi tramite <see cref="IDesignComponent"/>,
/// senza bisogno di distinguerli esplicitamente.
/// </summary>
public static class FormCodeGenerator
{
    public static (string RazorPath, string DesignerCsPath) Generate(
        string pagesDirectory,
        string formName,
        string razorNamespace,
        IReadOnlyList<PlacedControl> controls)
    {
        Directory.CreateDirectory(pagesDirectory);

        var razorPath = Path.Combine(pagesDirectory, $"{formName}.razor");
        var designerCsPath = Path.Combine(pagesDirectory, $"{formName}.razor.designer.cs");

        File.WriteAllText(razorPath, GenerateRazor(formName, controls));
        File.WriteAllText(designerCsPath, GenerateDesignerCs(formName, razorNamespace, controls));

        return (razorPath, designerCsPath);
    }

    private static string GenerateRazor(string formName, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"@page \"/{formName.ToLowerInvariant()}\"");
        sb.AppendLine();
        sb.AppendLine($"<PageTitle>{formName}</PageTitle>");
        sb.AppendLine();
        // CascadingValue distribuisce IsDesignMode a tutti i controlli, visuali e non-visuali:
        // e' l'unico punto che legge l'URL, i componenti a valle si limitano a consumarlo
        // (modulo 13 - primo uso reale del flag ?design=true introdotto nel modulo 10).
        sb.AppendLine("<CascadingValue Value=\"IsDesignMode\">");
        // Griglia di allineamento visiva, solo in design mode (vincolo architetturale n.5:
        // stesso bundle, pilotato da un flag - niente puntini nell'app reale a runtime).
        // La dimensione (16px) deve corrispondere a GridSize in MainWindow.axaml.cs (snap
        // al piazzamento), altrimenti i controlli non cadrebbero visivamente sui puntini.
        // GridBackgroundStyle (in GenerateDesignerCs) invece di un ternario inline: un
        // ternario con stringhe letterali dentro un attributo HTML gia' delimitato da
        // doppi apici romperebbe il parsing Razor (apici annidati).
        // id fisso: permette allo script iniettato in MainWindow (ponte JS per il click su
        // WebView2, dove i click nativi non arrivano mai ad Avalonia) di calcolare le
        // coordinate del click relative a QUESTO contenitore, le stesse usate da
        // LayoutBox.X/Y - non alle coordinate della finestra o della pagina intera.
        sb.AppendLine("""<div id="ide-design-surface" style="position:relative;width:100%;height:600px;@GridBackgroundStyle">""");
        foreach (var control in controls)
        {
            // Modulo 9 (generalizzato a N eventi per controllo, non piu' uno solo): il
            // markup collega un evento solo se e' di tipo "WireInMarkup" (es. VbButton.OnClick,
            // un EventCallback) e ha gia' del codice non-vuoto in {Form}.Behavior.cs
            // (control.WiredMethods) - altrimenti il metodo non esisterebbe ancora e la
            // compilazione fallirebbe. Gli eventi code-behind (es. VbTimer.Tick) vengono
            // collegati in GenerateDesignerCs, non qui.
            var eventAttributes = ComponentEventInfo.ForAll(control.ControlType)
                .Where(info => info.WireInMarkup && control.WiredMethods.Contains(info.EventName))
                .Select(info => $" {info.EventName}=\"{control.FieldName}{info.MethodSuffix}\"");
            sb.AppendLine($"    <{control.ControlType} Visual=\"{control.FieldName}\"{string.Concat(eventAttributes)} />");
        }
        sb.AppendLine("</div>");
        sb.AppendLine("</CascadingValue>");

        return sb.ToString();
    }

    private static string GenerateDesignerCs(string formName, string razorNamespace, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Questo file e' generato dal designer di Ide.App. Non modificarlo a mano:");
        sb.AppendLine("// verra' sovrascritto ad ogni modifica del form nel designer.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using VbControls;");
        sb.AppendLine("using VbControls.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {razorNamespace};");
        sb.AppendLine();
        // Implementa sempre IDisposable, a prescindere da quanti Distruttori sono cablati
        // oggi: cosi' l'interfaccia non compare/sparisce a seconda di cosa l'utente
        // scrive nella property grid, il che potrebbe rompere codice in {Form}.Behavior.cs
        // scritto nel frattempo presupponendo che IDisposable ci sia.
        sb.AppendLine($"public partial class {formName} : IDisposable");
        sb.AppendLine("{");

        // Modulo 13: IsDesignMode letto una sola volta qui e ridistribuito via
        // CascadingValue nel .razor, invece che ogni componente rilegga l'URL per conto suo.
        sb.AppendLine("    [Inject]");
        sb.AppendLine("    protected NavigationManager NavigationManager { get; set; } = default!;");
        sb.AppendLine();
        sb.AppendLine("    protected bool IsDesignMode => NavigationManager.Uri.Contains(\"design=true\", StringComparison.OrdinalIgnoreCase);");
        sb.AppendLine();
        // Griglia di allineamento visiva, solo in design mode (vincolo architetturale n.5:
        // stesso bundle, pilotato da un flag - niente puntini nell'app reale a runtime). La
        // dimensione (16px) deve corrispondere a GridSize in MainWindow.axaml.cs (snap al
        // piazzamento), altrimenti i controlli non cadrebbero visivamente sui puntini.
        sb.AppendLine("    protected string GridBackgroundStyle => IsDesignMode");
        sb.AppendLine("        ? \"background-image:radial-gradient(circle, #bbb 1px, transparent 1px); background-size:16px 16px;\"");
        sb.AppendLine("        : string.Empty;");
        sb.AppendLine();

        foreach (var control in controls)
        {
            sb.AppendLine($"    protected {control.Visual.GetType().Name} {control.FieldName} {{ get; }} = new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        LayoutBox = {EmitLayoutBox(control.Visual.LayoutBox)},");
            // Le proprieta' [VisualProperty] (modulo 8) sono cio' che l'utente personalizza
            // tramite la Property Grid: qui vengono serializzate cosi' come sono nell'istanza.
            foreach (var property in VisualPropertyReader.GetEditableProperties(control.Visual))
                sb.AppendLine($"        {property.Name} = {EmitValue(property.GetValue(control.Visual))},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        // Eventi code-behind (es. VbTimer.Tick, un vero event .NET sull'istanza "Visual",
        // a differenza di VbButton.OnClick che e' un parametro Blazor collegato nel .razor):
        // tutti quelli attivi per questo form condividono un solo OnInitialized generato,
        // insieme alle chiamate ai Costruttori (sempre disponibili, indipendenti dal tipo).
        var constructorWiring = controls.Where(c => c.WiredMethods.Contains(SpecialMethodNames.Constructor)).ToList();
        var destructorWiring = controls.Where(c => c.WiredMethods.Contains(SpecialMethodNames.Destructor)).ToList();
        var codeBehindWiring = controls
            .SelectMany(c => ComponentEventInfo.ForAll(c.ControlType)
                .Where(info => !info.WireInMarkup && c.WiredMethods.Contains(info.EventName))
                .Select(info => (Control: c, Info: info)))
            .ToList();

        if (constructorWiring.Count > 0 || codeBehindWiring.Count > 0)
        {
            sb.AppendLine("    protected override void OnInitialized()");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnInitialized();");
            foreach (var control in constructorWiring)
                sb.AppendLine($"        {SpecialMethodNames.ConstructorMethodName(control.FieldName)}();");
            foreach (var (control, info) in codeBehindWiring)
                sb.AppendLine($"        {control.FieldName}.{info.EventName} += {control.FieldName}{info.MethodSuffix};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        foreach (var control in destructorWiring)
            sb.AppendLine($"        {SpecialMethodNames.DestructorMethodName(control.FieldName)}();");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitLayoutBox(LayoutBox box) =>
        $"new LayoutBox {{ X = {EmitDouble(box.X)}, Y = {EmitDouble(box.Y)}, Width = {EmitDouble(box.Width)}, Height = {EmitDouble(box.Height)} }}";

    private static string EmitValue(object? value) => value switch
    {
        null => "null",
        string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        bool b => b ? "true" : "false",
        int i => i.ToString(CultureInfo.InvariantCulture),
        double d => EmitDouble(d),
        _ => throw new NotSupportedException(
            $"FormCodeGenerator non sa serializzare un valore di tipo {value.GetType()} " +
            "(tipi supportati per [VisualProperty]: string, bool, int, double)."),
    };

    private static string EmitDouble(double value) => value.ToString(CultureInfo.InvariantCulture);
}

/// <summary>
/// Riflessione condivisa tra generatore di codice (modulo 7) e Property Grid (modulo 8)
/// sulle proprieta' marcate <see cref="VisualPropertyAttribute"/>: e' cosi' che entrambi
/// restano sempre d'accordo su cosa e' editabile per un dato componente, visuale o no
/// (modulo 13).
/// </summary>
public static class VisualPropertyReader
{
    public static IEnumerable<PropertyInfo> GetEditableProperties(IDesignComponent component) =>
        component.GetType()
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetCustomAttribute<VisualPropertyAttribute>() is not null && p.CanRead && p.CanWrite);
}
