using System.Globalization;
using System.Reflection;
using System.Text;
using VbControls.Abstractions;

namespace Ide.Designer;

/// <summary>
/// Modulo 7: genera i due file posseduti dal designer per ogni Form
/// (vincolo architetturale n.3): <c>{Form}.razor</c> e <c>{Form}.razor.designer.cs</c>.
/// Il terzo file, <c>{Form}.Behavior.cs</c>, e' scritto dallo sviluppatore e non viene
/// mai toccato da questa classe.
/// Rigenera sempre l'intero contenuto a partire dal modello in memoria: e' sicuro perche'
/// questi file non sono editati a mano.
/// Modulo 13: i controlli possono essere visuali o non-visuali (sezione 2.1 di
/// ARCHITECTURE.md) - il generatore tratta entrambi tramite <see cref="IDesignComponent"/>,
/// senza bisogno di distinguerli esplicitamente.
/// </summary>
public static class FormCodeGenerator
{
    public static (string RazorPath, string DesignerCsPath) Generate(
        string pagesDirectory,
        string formName,
        string razorNamespace,
        IReadOnlyList<PlacedControl> controls)
    {
        Directory.CreateDirectory(pagesDirectory);

        var razorPath = Path.Combine(pagesDirectory, $"{formName}.razor");
        var designerCsPath = Path.Combine(pagesDirectory, $"{formName}.razor.designer.cs");

        File.WriteAllText(razorPath, GenerateRazor(formName, controls));
        File.WriteAllText(designerCsPath, GenerateDesignerCs(formName, razorNamespace, controls));

        return (razorPath, designerCsPath);
    }

    private static string GenerateRazor(string formName, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"@page \"/{formName.ToLowerInvariant()}\"");
        sb.AppendLine();
        sb.AppendLine($"<PageTitle>{formName}</PageTitle>");
        sb.AppendLine();
        // CascadingValue distribuisce IsDesignMode a tutti i controlli, visuali e non-visuali:
        // e' l'unico punto che legge l'URL, i componenti a valle si limitano a consumarlo
        // (modulo 13 - primo uso reale del flag ?design=true introdotto nel modulo 10).
        sb.AppendLine("<CascadingValue Value=\"IsDesignMode\">");
        sb.AppendLine("""<div style="position:relative;width:100%;height:600px;">""");
        foreach (var control in controls)
        {
            // Modulo 9: il markup collega l'evento solo se il doppio click ha gia'
            // generato l'handler corrispondente in {Form}.Behavior.cs - altrimenti il
            // metodo non esisterebbe ancora e la compilazione fallirebbe.
            var onClick = control is { ControlType: "VbButton", HasClickHandler: true }
                ? $" OnClick=\"{control.FieldName}_Click\""
                : string.Empty;
            sb.AppendLine($"    <{control.ControlType} Visual=\"{control.FieldName}\"{onClick} />");
        }
        sb.AppendLine("</div>");
        sb.AppendLine("</CascadingValue>");

        return sb.ToString();
    }

    private static string GenerateDesignerCs(string formName, string razorNamespace, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Questo file e' generato dal designer di Ide.App. Non modificarlo a mano:");
        sb.AppendLine("// verra' sovrascritto ad ogni modifica del form nel designer.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using VbControls;");
        sb.AppendLine("using VbControls.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {razorNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {formName}");
        sb.AppendLine("{");

        // Modulo 13: IsDesignMode letto una sola volta qui e ridistribuito via
        // CascadingValue nel .razor, invece che ogni componente rilegga l'URL per conto suo.
        sb.AppendLine("    [Inject]");
        sb.AppendLine("    protected NavigationManager NavigationManager { get; set; } = default!;");
        sb.AppendLine();
        sb.AppendLine("    protected bool IsDesignMode => NavigationManager.Uri.Contains(\"design=true\", StringComparison.OrdinalIgnoreCase);");
        sb.AppendLine();

        foreach (var control in controls)
        {
            sb.AppendLine($"    protected {control.Visual.GetType().Name} {control.FieldName} {{ get; }} = new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        LayoutBox = {EmitLayoutBox(control.Visual.LayoutBox)},");
            // Le proprieta' [VisualProperty] (modulo 8) sono cio' che l'utente personalizza
            // tramite la Property Grid: qui vengono serializzate cosi' come sono nell'istanza.
            foreach (var property in VisualPropertyReader.GetEditableProperties(control.Visual))
                sb.AppendLine($"        {property.Name} = {EmitValue(property.GetValue(control.Visual))},");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitLayoutBox(LayoutBox box) =>
        $"new LayoutBox {{ X = {EmitDouble(box.X)}, Y = {EmitDouble(box.Y)}, Width = {EmitDouble(box.Width)}, Height = {EmitDouble(box.Height)} }}";

    private static string EmitValue(object? value) => value switch
    {
        null => "null",
        string s => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
        bool b => b ? "true" : "false",
        int i => i.ToString(CultureInfo.InvariantCulture),
        double d => EmitDouble(d),
        _ => throw new NotSupportedException(
            $"FormCodeGenerator non sa serializzare un valore di tipo {value.GetType()} " +
            "(tipi supportati per [VisualProperty]: string, bool, int, double)."),
    };

    private static string EmitDouble(double value) => value.ToString(CultureInfo.InvariantCulture);
}

/// <summary>
/// Riflessione condivisa tra generatore di codice (modulo 7) e Property Grid (modulo 8)
/// sulle proprieta' marcate <see cref="VisualPropertyAttribute"/>: e' cosi' che entrambi
/// restano sempre d'accordo su cosa e' editabile per un dato componente, visuale o no
/// (modulo 13).
/// </summary>
public static class VisualPropertyReader
{
    public static IEnumerable<PropertyInfo> GetEditableProperties(IDesignComponent component) =>
        component.GetType()
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.GetCustomAttribute<VisualPropertyAttribute>() is not null && p.CanRead && p.CanWrite);
}
