using System.Text;

namespace Ide.Designer;

/// <summary>
/// Modulo 7: genera i due file posseduti dal designer per ogni Form
/// (vincolo architetturale n.3): <c>{Form}.razor</c> e <c>{Form}.razor.designer.cs</c>.
/// Il terzo file, <c>{Form}.Behavior.cs</c>, e' scritto dallo sviluppatore e non viene
/// mai toccato da questa classe.
/// Rigenera sempre l'intero contenuto a partire dal modello in memoria: e' sicuro perche'
/// questi file non sono editati a mano.
/// </summary>
public static class FormCodeGenerator
{
    private static readonly IReadOnlyDictionary<string, string> VisualTypeByControlType = new Dictionary<string, string>
    {
        ["VbButton"] = "VbButtonVisual",
        ["VbLabel"] = "VbLabelVisual",
        ["VbTextBox"] = "VbTextBoxVisual",
    };

    public static (string RazorPath, string DesignerCsPath) Generate(
        string pagesDirectory,
        string formName,
        string razorNamespace,
        IReadOnlyList<PlacedControl> controls)
    {
        Directory.CreateDirectory(pagesDirectory);

        var razorPath = Path.Combine(pagesDirectory, $"{formName}.razor");
        var designerCsPath = Path.Combine(pagesDirectory, $"{formName}.razor.designer.cs");

        File.WriteAllText(razorPath, GenerateRazor(formName, controls));
        File.WriteAllText(designerCsPath, GenerateDesignerCs(formName, razorNamespace, controls));

        return (razorPath, designerCsPath);
    }

    private static string GenerateRazor(string formName, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"@page \"/{formName.ToLowerInvariant()}\"");
        sb.AppendLine();
        sb.AppendLine($"<PageTitle>{formName}</PageTitle>");
        sb.AppendLine();
        sb.AppendLine("""<div style="position:relative;width:100%;height:600px;">""");
        foreach (var control in controls)
            sb.AppendLine($"    <{control.ControlType} Visual=\"{control.FieldName}\" />");
        sb.AppendLine("</div>");

        return sb.ToString();
    }

    private static string GenerateDesignerCs(string formName, string razorNamespace, IReadOnlyList<PlacedControl> controls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Questo file e' generato dal designer di Ide.App. Non modificarlo a mano:");
        sb.AppendLine("// verra' sovrascritto ad ogni modifica del form nel designer.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using VbControls;");
        sb.AppendLine("using VbControls.Abstractions;");
        sb.AppendLine();
        sb.AppendLine($"namespace {razorNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {formName}");
        sb.AppendLine("{");
        foreach (var control in controls)
        {
            var visualType = VisualTypeByControlType[control.ControlType];
            sb.AppendLine($"    protected {visualType} {control.FieldName} {{ get; }} = new()");
            sb.AppendLine("    {");
            sb.AppendLine($"        LayoutBox = new LayoutBox {{ X = {control.X:0}, Y = {control.Y:0}, Width = {control.Width:0}, Height = {control.Height:0} }}");
            sb.AppendLine("    };");
            sb.AppendLine();
        }
        sb.AppendLine("}");

        return sb.ToString();
    }
}
